### ISSUE TITLE
Abstract implementation of ISnapshot for convenience

### ISSUE THREAD

**Issue by SurajGupta** [jonsequitur/Its.Cqrs#109]
Should Domain contain an abstract implementation of ISnapshot for convenience?  Would make concrete snapshots more readable because they could extend the abstract Snapshot and skip the boiler-plate properties (AggregateId, Version, etc.).

**Comment by jonsequitur** [comment]
It would probably be useful and I'm not opposed to it. I'm not really satisfied with `ISnapshot` and that's probably why it wasn't done before. I'm not a proponent of interfaces with properties and an interface with setters seems even more awkward to me. I'd prefer to clean up the interface first. 

Suggestions are of course welcome.

**Comment by SurajGupta** [comment]
Agreed, an interface with properties is typically a code smell.  How about just using an abstract Snapshot class with properties for each of the ISnapshot properties?  You could make those properties virtual too?

**Comment by jonsequitur** [comment]
Hi Suraj, 

The following PR includes an alternate approach and I'm curious what you think of it. It removes the requirement that you implement `ISnapshot` by providing a built-in implementation that will serialize the state of the aggregate itself, including private fields, using NewtonSoft.Json. The advantage is it "just works" but the disadvantage is that you need to make sure your aggregate is fully serializable, including internal state. It's a tradeoff but I think that it's less work and more robust.

https://github.com/jonsequitur/Its.Cqrs/pull/128/files?w=t

**Comment by SurajGupta** [comment]
Hi Jon,

I agree - this seems less work and more robust.  I believe that for a majority of scenarios where aggregates are properly designed/scoped, serialization/deserialization will just work.  In the cases where something more complicated is required, the user can register a custom serializer.  

With this solution, is the utility of ISnapshot constrained to inflating an Aggregate?  Since there is no concrete implementation of ISnapshot, we don't have access to the Aggregate's snapshotted properties.  Perhaps inflating Aggregates was always the primary use case for an ISnapshot.  Excuse the stupid questions - I'm still ramping-up on this project.  

@wlscaudill - heads-up and thoughts?

**Comment by jonsequitur** [comment]
The sole purpose of a snapshot is to source an aggregate without having to re-read its entire event stream. Ideally, your code should behave identically whether the aggregate was sourced from events, from a snapshot, or from a combination of the two (e.g. from a snapshot with a few later events then applied.)

**Comment by SurajGupta** [comment]
Thanks!  Yeah, I think this is a pretty awesome solution then.
