### ISSUE TITLE
Failed Command Deserialization catastrophically fails ClockTrigger.AdvanceClock

### ISSUE THREAD

**Issue by PhillipPruett** [jonsequitur/Its.Cqrs#116]
when ClockTrigger.AdvanceClock picks up a command that it fails to deserialize (which can happen with command definitions changing over time) then the entire process catastrophically fails resulting in an exception and no commands being applied.

Feels similar to https://github.com/jonsequitur/Its.Cqrs/issues/74 so a fix may solve both

**Comment by jonsequitur** [comment]
Do you have a stack trace?

**Comment by PhillipPruett** [comment]
I've pinned the failure with a new test in [this forked branch](https://github.com/PhillipPruett/Its.Cqrs/tree/ClockTriggerAdvanceClockThrowsOnDeserializationFailure).

will work on a fix and send a pull request.
