### ISSUE TITLE
What is URL structure in Sample.Domain.Api

### ISSUE THREAD

**Issue by SurajGupta** [jonsequitur/Its.Cqrs#55]
Question - I'm running the Smaple.Domain.Api WebAPI app.  What is the URL structure?  Could you provide some sample URLs that I could hit to generate events?  I looked at the OrderApiController which extends DomainApiController<Order>, which seems to do some cool/magic wire-up of event-sourced assembly, I just can't figure out how to use it!

**Comment by jonsequitur** [comment]
Apologies, this sample hasn't received a lot of love. You can see the routing rules here: https://github.com/jonsequitur/Its.Cqrs/blob/master/Domain.Api/HttpConfigurationExtensions.cs

It sets these up by convention by discovering your command types at runtime.

**Comment by SurajGupta** [comment]
Hi Jon - I'm still struggling to get this to work.  I've tried various combinations of "Order" "Api" and "Help" with dashes in the URL.  Can you paste a specific URL that will work/put me in the debugger?  I think if I have one example I can figure out the rest.

**Comment by jonsequitur** [comment]
You can see a bunch of examples in the tests here: https://github.com/jonsequitur/Its.Cqrs/blob/master/Domain.Api.Tests/CommandDispatchTests.cs

**Comment by SurajGupta** [comment]
thanks!
