### ISSUE TITLE
Mark assemblies CLS-compliant

### ISSUE THREAD

**Issue by SurajGupta** [jonsequitur/Its.Cqrs#71]
Can the Domain projects be marked as CLS-compliant?  Would allow for CLS-compliant projects to cleanly consume Its.Domain.*

**Comment by jonsequitur** [comment]
Easy enough!

Resolved with https://github.com/jonsequitur/Its.Cqrs/commit/f54b38ef1880cc230ed2a1115aa93b080ca736eb and packages updated in NuGet.

**Comment by SurajGupta** [comment]
thanks for the quick turnaround!!!
