### ISSUE TITLE
Exceptions thrown by HandleScheduledCommandException methods are not handled

### ISSUE THREAD

**Issue by charlesmccarthyirl** [jonsequitur/Its.Cqrs#74]
EventSourcedRepositoryExtensions.FailScheduledCommand. No try/catch around
await scheduledCommandOfT.Handler
                                             .HandleScheduledCommandException((dynamic) aggregate,
                                                                              (dynamic) failure);
This causes ApplyScheduledCommand to fail

**Comment by jonsequitur** [comment]
I've been trying to figure out whether this is actually just fine. I think `ApplyScheduledCommand` should fail in this case, and I'm not sure what we could do by handling the exception.

Any suggestions?

**Comment by charlesmccarthyirl** [comment]
It seemed to fail advancing the clock at the time (i.e. no other commands would get executed). I don't know if this is still the case. Catching the exception and maybe logging it to the failed commands database I think may be better. It would be good if it was highlighted through the pipeline too so the consuming code could log the event.

**Comment by jonsequitur** [comment]
The fix for the bug that Phillip linked will also prevent the scheduler from failing overall. At that point I'm less incline to build an error handling / logging strategy into the framework. Whoever's calling `AdvanceClock` should just handle the exception.
