### ISSUE TITLE
Performance improvements for catchup query to the event store

### ISSUE THREAD

**Issue by charlesmccarthyirl** [jonsequitur/Its.Cqrs#79]
Time-to-first-row on a ~4 million row event store is ~30 seconds. It also seems to put the sql server under memory load. Adding a different index might help. 

Queries such as the following are generated::

exec sp_executesql N'SELECT 
    [Project1].[AggregateId] AS [AggregateId], 
    [Project1].[SequenceNumber] AS [SequenceNumber], 
    [Project1].[Id] AS [Id], 
    [Project1].[StreamName] AS [StreamName], 
    [Project1].[Type] AS [Type], 
    [Project1].[UtcTime] AS [UtcTime], 
    [Project1].[Actor] AS [Actor], 
    [Project1].[Body] AS [Body], 
    [Project1].[ETag] AS [ETag]
    FROM ( SELECT 
        [Extent1].[AggregateId] AS [AggregateId], 
        [Extent1].[SequenceNumber] AS [SequenceNumber], 
        [Extent1].[Id] AS [Id], 
        [Extent1].[StreamName] AS [StreamName], 
        [Extent1].[Type] AS [Type], 
        [Extent1].[UtcTime] AS [UtcTime], 
        [Extent1].[Actor] AS [Actor], 
        [Extent1].[Body] AS [Body], 
        [Extent1].[ETag] AS [ETag]
        FROM [EventStore].[Events] AS [Extent1]
        WHERE ((@p__linq__0 = 1) OR ([Extent1].[StreamName] IN (N''Stream1'', N''Stream2''))) AND ((@p__linq__1 = 1) OR ([Extent1].[Type] IN (N''Type1'', N''Type2'', N''Type3'', N''Type4'', N''Type5'', N''Type6'', N''Type7'', N''Type8'', N''Type9'', N''Type10'', N''Type11'', N''Type12'', N''Type13'', N''Type14'', N''Type15'', N''Type16'', N''Type17'', N''Type18'', N''Type19'', N''Type20'', N''Type21''))) AND ([Extent1].[Id] >= @p__linq__2)
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC',N'@p__linq__0 bit,@p__linq__1 bit,@p__linq__2 bigint',@p__linq__0=0,@p__linq__1=0,@p__linq__2=1
go

**Comment by charlesmccarthyirl** [comment]
I noticed that adding an index as follows brings the time down to milliseconds and significantly less CPU and memory load on SQL:

CREATE NONCLUSTERED INDEX [IX_Id_Type] ON [EventStore].[Events]
(
	[Id] ASC,
	[Type]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

**Comment by jonsequitur** [comment]
Resolved as part of #101.
