### ISSUE TITLE
Performance improvements for sourcing an aggregate for a large number of events

### ISSUE THREAD

**Issue by charlesmccarthyirl** [jonsequitur/Its.Cqrs#99]
Sourcing an aggregate even from events with empty Update methods is very slow when there are a large number of events

**Comment by jonsequitur** [comment]
Can you provide some numbers?

This is just a matter of a large number of invocations being slow. A non-empty `Update` is going to be slower than an empty one. In any case, calling `Update` isn't optional, and I think that an empty `Update` method is a bit of a code smell. Why does the domain event exist if it has no significance for the aggregate's state?

**Comment by charlesmccarthyirl** [comment]
I was profiling sourcing aggregates from our pre-production events as to why they were so slow. 30k events was maxing a cpu core for 60 seconds. Main culprits from Its.Cqrs were an O(n^2) approach in EventSequence and also the GetHashCode used on events. Getting rid of those brought it down to ~30 seconds (the rest of the inefficiencies are in our own code). The inefficiencies are there for any events, so when I say events with no Update, I just mean pure Its.Cqrs overhead on sourcing.

I have a branch working on it - it's almost done. Just need to finish another test or two and I'll send a pull request

**Comment by charlesmccarthyirl** [comment]
Created a pull request for it. For the 30k event test added - the changes brought the time down from ~20 seconds to ~2 seconds

**Comment by jonsequitur** [comment]
Very nice!

**Comment by jonsequitur** [comment]
Resolved by #107.
